title:                  "Chassis - CSS"
baseURL:                "https://chassis-ui.com/css/"

docsDir:                "site"
docsPath:                "/css/docs"

subtitle:               "A Tokenized CSS Framework Bridging Figma to Production Code"
description:            "An open-source, tokenized CSS framework that bridges Figma designs to production code with semantic context classes and a multi-brand color system."
authors:                "Ozgur Gunes and Bootstrap contributers"

current_version:        "0.1.2"
github_org:             "https://github.com/ozgurgunes"
repo:                   "https://github.com/chassis-ui/css"
blog:                   "https://chassis-ui.com/blog/"
x:                      "chassis_ui"

analytics:
  google_id:            "G-QGR8C28VYN"

algolia:
  app_id:               "TMI5N9J6TZ"
  api_key:              "e318e0636b0a951e4f82c8283345df13"
  index_name:           "chassis-docs"


download:
  source:               "https://github.com/chassis-ui/css/archive/v0.1.2.zip"
  dist:                 "https://github.com/chassis-ui/css/releases/download/v0.1.2/chassis-css-0.1.2-dist.zip"

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:                  "https://cdn.jsdelivr.net/gh/chassis-ui/css@app/docs/dist/css/chassis.min.css"
  css_hash:             "sha384-bxP3Rs/HDmPhl81b9duNsO1Y+sTnmUlEZbs1a8TN2fSnmS7mIlzuUnAUmh/mKw+g"
  css_rtl:              "https://cdn.jsdelivr.net/gh/chassis-ui/css@app/docs/dist/css/chassis.rtl.min.css"
  css_rtl_hash:         "sha384-eXtkxl2IKlML4iyZdpOCn3VXZdk4K+Ei0kg941nP7whrw9zbrRwNynncuaZBUdkg"
  js:                   "https://cdn.jsdelivr.net/gh/chassis-ui/css@app/docs/dist/js/chassis.min.js"
  js_hash:              "sha384-CRSviWK09lVsZYJ+Eqz8DgIoU3gyQRS9ZVQVN+WsDM/43jikTrV10tWjaGzpCnYS"
  js_bundle:            "https://cdn.jsdelivr.net/gh/chassis-ui/css@app/docs/dist/js/chassis.bundle.min.js"
  js_bundle_hash:       "sha384-xshy/GhjPnSCRAe52qcnDkpMkkzsspSbj19YuctPDsvgf84XUtaQJINh8ALpd934"
  popper:               "https://cdn.jsdelivr.net/gh/chassis-ui/css@app/docs/dist/js/popper.min.js"
  popper_hash:          "sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
  popper_esm:           "https://cdn.jsdelivr.net/gh/chassis-ui/css@app/docs/dist/js/popper.esm.min.js"

anchors:
  min:                  2
  max:                  5

toc:
  min:                  2
  max:                  6
