#!/usr/bin/env node

/*!
 * test-merge.mjs — Node-only regression test for dist/tailwind/merge.js,
 * the tailwind-merge classGroups config generated by
 * build/tailwind/build-merge.mjs from scss/tailwind/merge-manifest.scss.
 * Imports the real, built dist/tailwind/merge.js (not a fixture) and the
 * real `tailwind-merge` package, and asserts on actual `extendTailwindMerge`
 * / `twMerge` behavior, not just the shape of the generated config.
 *
 * Run via `pnpm css:test:tailwind` (wired into `pnpm test`).
 *
 * Copyright 2026 Ozgur Gunes
 * Licensed under MIT (https://github.com/chassis-ui/css/blob/main/LICENSE)
 */

import assert from 'node:assert/strict'
import path from 'node:path'
import { describe, test } from 'node:test'
import { fileURLToPath } from 'node:url'
import { extendTailwindMerge } from 'tailwind-merge'

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(here, '../../..')

const { classGroups, overrideClassGroups } = await import(path.join(root, 'dist/tailwind/merge.js'))
const twMerge = extendTailwindMerge({
  override: { classGroups: overrideClassGroups },
  extend: { classGroups }
})

describe('dist/tailwind/merge.js', () => {
  test("groups are keyed by the utility map's own top-level keys", () => {
    assert.ok(classGroups['fg-color'], 'expected a "fg-color" group')
    assert.ok(classGroups.margin, 'expected a "margin" group')
    assert.ok(Object.keys(classGroups).length > 50, 'expected dozens of groups')
  })

  test('conflicting classes from the same utility resolve to the last one (twMerge)', () => {
    assert.equal(twMerge('fg-primary', 'fg-danger'), 'fg-danger')
    assert.equal(twMerge('m-sm', 'm-lg'), 'm-lg')
  })

  test('the placement classes of .grid resolve in the groups of tailwind-merge itself', () => {
    // They are Tailwind core utilities, so the manifest lists none of them,
    // and the groups of the removed flexbox grid and of its aliases are gone.
    for (const group of [
      'grid-col',
      'grid-row-cols',
      'grid-offset',
      'grid-gutter',
      'grid-gutter-x',
      'grid-gutter-y',
      'col-start-end',
      'col-start'
    ]) {
      assert.equal(classGroups[group], undefined, `unexpected "${group}" group`)
    }
    assert.equal(twMerge('col-span-4', 'col-span-6'), 'col-span-6')
    assert.equal(twMerge('md:col-span-4', 'md:col-span-6'), 'md:col-span-6')
    assert.equal(twMerge('col-span-4', 'md:col-span-6'), 'col-span-4 md:col-span-6')
    assert.equal(twMerge('col-start-2', 'col-start-auto'), 'col-start-auto')
    assert.equal(twMerge('grid-cols-2', 'grid-cols-4'), 'grid-cols-4')
    assert.equal(twMerge('grid-rows-2', 'grid-rows-3'), 'grid-rows-3')
  })

  test("the width classes join tailwind-merge's own width group", () => {
    // tailwind-merge resolves `w-6/12` to its `w` group, so the Chassis
    // widths are listed there: a fraction then conflicts with `w-100`,
    // `w-auto` and the percentage and token widths.
    assert.ok(classGroups.w.includes('w-100'))
    assert.ok(classGroups.w.includes('w-6/12'))
    assert.equal(classGroups.width, undefined)
    assert.equal(classGroups['width-fraction'], undefined)
    assert.equal(twMerge('w-50', 'w-100'), 'w-100')
    assert.equal(twMerge('w-md', 'w-auto'), 'w-auto')
    assert.equal(twMerge('w-6/12', 'w-auto'), 'w-auto')
    assert.equal(twMerge('w-100', 'w-6/12'), 'w-6/12')
    assert.equal(twMerge('md:w-6/12', 'md:w-100'), 'md:w-100')
    assert.equal(twMerge('w-6/12', 'lg:w-auto'), 'w-6/12 lg:w-auto')
    assert.equal(twMerge('w-100', 'h-100'), 'w-100 h-100')
  })

  test('a Chassis class that has the name of a Tailwind utility is kept', () => {
    // `.grid`, `.table`, `.inline`, `.list-item`, `.collapse` and `.static`
    // are Chassis classes in the entry (`_source-exclusions.scss`), which
    // tailwind-merge lists in its display, visibility and position groups.
    assert.deepEqual(Object.keys(overrideClassGroups), ['display', 'position', 'visibility'])
    for (const name of ['grid', 'table', 'inline', 'list-item']) {
      assert.ok(!overrideClassGroups.display.includes(name), `"${name}" in the display group`)
    }
    assert.ok(!overrideClassGroups.visibility.includes('collapse'))
    assert.ok(!overrideClassGroups.position.includes('static'))

    assert.equal(twMerge('grid gap-md', 'd-flex'), 'grid gap-md d-flex')
    assert.equal(twMerge('grid', 'd-grid'), 'grid d-grid')
    assert.equal(twMerge('grid', 'md:d-none'), 'grid md:d-none')
    assert.equal(twMerge('table', 'd-block'), 'table d-block')
    assert.equal(twMerge('list-item', 'd-flex'), 'list-item d-flex')
    assert.equal(twMerge('collapse', 'invisible'), 'collapse invisible')
    assert.equal(twMerge('drawer static', 'position-relative'), 'drawer static position-relative')
  })

  test("the display utilities still resolve against each other and against Tailwind's own", () => {
    assert.equal(twMerge('d-flex', 'd-grid'), 'd-grid')
    assert.equal(twMerge('flex', 'd-none'), 'd-none')
    assert.equal(twMerge('d-flex', 'hidden'), 'hidden')
    assert.equal(twMerge('visible', 'invisible'), 'invisible')
    assert.equal(twMerge('position-relative', 'absolute'), 'absolute')
  })

  test('without the override, the documented reason for it holds', () => {
    // The defect the override removes; if tailwind-merge stops listing
    // `grid` in its display group, the override can go.
    const extendOnly = extendTailwindMerge({ extend: { classGroups } })
    assert.equal(extendOnly('grid', 'd-flex'), 'd-flex')
  })

  test('classes from different groups are both kept', () => {
    assert.equal(twMerge('fg-primary', 'm-sm'), 'fg-primary m-sm')
  })

  test('non-Chassis, non-Tailwind classes pass through untouched', () => {
    assert.equal(
      twMerge('button', 'primary', 'fg-primary', 'fg-danger'),
      'button primary fg-danger'
    )
  })

  test('attribute-selector utilities (no enumerable class name) are absent', () => {
    assert.equal(classGroups['aspect-ratio-attr'], undefined)
  })

  test('a dotted-compound utility is grouped under its own key by its base class name', () => {
    assert.ok(classGroups['font-display-size']?.includes('font-5xl'))
  })

  test('disabled utility entries produce no group', () => {
    // "elevation-shadow" / "shadow-color" are gated behind
    // $enable-elevation-shadows in scss/config/_defaults.scss; if a future
    // config change disables them by default this assertion should be
    // revisited rather than silently going stale.
    for (const [group, classes] of Object.entries(classGroups)) {
      assert.ok(classes.length > 0, `group "${group}" should not be empty`)
    }
  })
})
