#!/usr/bin/env node

/*!
 * test-merge.mjs — Node-only regression test for dist/tailwind/merge.js,
 * the tailwind-merge classGroups config generated by
 * build/tailwind/build-merge.mjs from scss/tailwind/merge-manifest.scss.
 * Imports the real, built dist/tailwind/merge.js (not a fixture) and the
 * real `tailwind-merge` package, and asserts on actual `extendTailwindMerge`
 * / `twMerge` behavior, not just the shape of the generated config.
 *
 * Run via `pnpm css:test:tailwind` (wired into `pnpm test`).
 *
 * Copyright 2026 Ozgur Gunes
 * Licensed under MIT (https://github.com/chassis-ui/css/blob/main/LICENSE)
 */

import assert from 'node:assert/strict'
import path from 'node:path'
import { describe, test } from 'node:test'
import { fileURLToPath } from 'node:url'
import { extendTailwindMerge } from 'tailwind-merge'

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(here, '../../..')

const { classGroups } = await import(path.join(root, 'dist/tailwind/merge.js'))
const twMerge = extendTailwindMerge({ extend: { classGroups } })

describe('dist/tailwind/merge.js', () => {
  test("groups are keyed by the utility map's own top-level keys", () => {
    assert.ok(classGroups['fg-color'], 'expected a "fg-color" group')
    assert.ok(classGroups.margin, 'expected a "margin" group')
    assert.ok(Object.keys(classGroups).length > 50, 'expected dozens of groups')
  })

  test('conflicting classes from the same utility resolve to the last one (twMerge)', () => {
    assert.equal(twMerge('fg-primary', 'fg-danger'), 'fg-danger')
    assert.equal(twMerge('m-sm', 'm-lg'), 'm-lg')
  })

  test('grid classes resolve within their own group', () => {
    // The grid classes are `@utility` rules too (scss/tailwind/_grid.scss),
    // listed by `generate-tailwind-grid-merge-manifest`.
    assert.equal(twMerge('col-6', 'col-4'), 'col-4')
    assert.equal(twMerge('col', 'col-auto'), 'col-auto')
    assert.equal(twMerge('md:col-6', 'md:col-4'), 'md:col-4')
    assert.equal(twMerge('col-6', 'md:col-4'), 'col-6 md:col-4')
    assert.equal(twMerge('row-cols-2', 'row-cols-4'), 'row-cols-4')
    assert.equal(twMerge('offset-2', 'offset-4'), 'offset-4')
    assert.equal(twMerge('g-md', 'g-lg'), 'g-lg')
    assert.equal(twMerge('gx-0', 'gx-md'), 'gx-md')
    assert.equal(twMerge('g-col-4', 'g-col-6'), 'g-col-6')
    assert.equal(twMerge('g-start-2', 'g-start-4'), 'g-start-4')
    assert.equal(twMerge('col-6', 'offset-2', 'g-col-4'), 'col-6 offset-2 g-col-4')
  })

  test('the deprecated g-col-*/g-start-* aliases share the groups of col-span-*/col-start-*', () => {
    // The placement classes of `.grid` are Tailwind core utilities, which
    // tailwind-merge groups on its own (`col-start-end`, `col-start`); the
    // manifest adds the aliases to those groups instead of making its own.
    assert.ok(classGroups['col-start-end'].includes('g-col-4'))
    assert.ok(classGroups['col-start'].includes('g-start-2'))
    assert.equal(classGroups['grid-g-col'], undefined)
    assert.equal(classGroups['grid-g-start'], undefined)
    assert.equal(twMerge('col-span-4', 'g-col-6'), 'g-col-6')
    assert.equal(twMerge('g-col-4', 'col-span-6'), 'col-span-6')
    assert.equal(twMerge('md:g-col-4', 'md:col-span-6'), 'md:col-span-6')
    assert.equal(twMerge('col-start-2', 'g-start-4'), 'g-start-4')
    assert.equal(twMerge('g-col-4', 'md:col-span-6'), 'g-col-4 md:col-span-6')
  })

  test('classes from different groups are both kept', () => {
    assert.equal(twMerge('fg-primary', 'm-sm'), 'fg-primary m-sm')
  })

  test('non-Chassis, non-Tailwind classes pass through untouched', () => {
    assert.equal(
      twMerge('button', 'primary', 'fg-primary', 'fg-danger'),
      'button primary fg-danger'
    )
  })

  test('attribute-selector utilities (no enumerable class name) are absent', () => {
    assert.equal(classGroups['aspect-ratio-attr'], undefined)
  })

  test('a dotted-compound utility is grouped under its own key by its base class name', () => {
    assert.ok(classGroups['font-display-size']?.includes('font-5xl'))
  })

  test('disabled utility entries produce no group', () => {
    // "elevation-shadow" / "shadow-color" are gated behind
    // $enable-elevation-shadows in scss/config/_defaults.scss; if a future
    // config change disables them by default this assertion should be
    // revisited rather than silently going stale.
    for (const [group, classes] of Object.entries(classGroups)) {
      assert.ok(classes.length > 0, `group "${group}" should not be empty`)
    }
  })
})
