#!/usr/bin/env node

/*!
 * test-merge.mjs — Node-only regression test for dist/tailwind/merge.js,
 * the tailwind-merge classGroups config generated by
 * build/tailwind/build-tailwind-merge.mjs from scss/tailwind/merge-manifest.scss.
 * Imports the real, built dist/tailwind/merge.js (not a fixture) and the
 * real `tailwind-merge` package, and asserts on actual `extendTailwindMerge`
 * / `twMerge` behavior, not just the shape of the generated config.
 *
 * Run via `pnpm css:test:tailwind` (wired into `pnpm test`).
 *
 * Copyright 2026 Ozgur Gunes
 * Licensed under MIT (https://github.com/chassis-ui/css/blob/main/LICENSE)
 */

import assert from 'node:assert/strict'
import path from 'node:path'
import { describe, test } from 'node:test'
import { fileURLToPath } from 'node:url'
import { extendTailwindMerge } from 'tailwind-merge'

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(here, '../../..')

const { classGroups } = await import(path.join(root, 'dist/tailwind/merge.js'))
const twMerge = extendTailwindMerge({ extend: { classGroups } })

describe('dist/tailwind/merge.js', () => {
  test("groups are keyed by the utility map's own top-level keys", () => {
    assert.ok(classGroups['fg-color'], 'expected a "fg-color" group')
    assert.ok(classGroups.margin, 'expected a "margin" group')
    assert.ok(Object.keys(classGroups).length > 50, 'expected dozens of groups')
  })

  test('conflicting classes from the same utility resolve to the last one (twMerge)', () => {
    assert.equal(twMerge('fg-primary', 'fg-danger'), 'fg-danger')
    assert.equal(twMerge('m-sm', 'm-lg'), 'm-lg')
  })

  test('classes from different groups are both kept', () => {
    assert.equal(twMerge('fg-primary', 'm-sm'), 'fg-primary m-sm')
  })

  test('non-Chassis, non-Tailwind classes pass through untouched', () => {
    assert.equal(
      twMerge('button', 'primary', 'fg-primary', 'fg-danger'),
      'button primary fg-danger'
    )
  })

  test('attribute-selector utilities (no enumerable class name) are absent', () => {
    assert.equal(classGroups['aspect-ratio-attr'], undefined)
  })

  test('a dotted-compound utility is grouped under its own key by its base class name', () => {
    assert.ok(classGroups['font-display-size']?.includes('font-5xl'))
  })

  test('disabled utility entries produce no group', () => {
    // "elevation-shadow" / "shadow-color" are gated behind
    // $enable-elevation-shadows in scss/config/_defaults.scss; if a future
    // config change disables them by default this assertion should be
    // revisited rather than silently going stale.
    for (const [group, classes] of Object.entries(classGroups)) {
      assert.ok(classes.length > 0, `group "${group}" should not be empty`)
    }
  })
})
